# Generated by Django 2.1.3 on 2019-02-26 04:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('n', 'none'), ('c', 'Currently reading'), ('r', 'Read'), ('w', 'want to read')], default='n', help_text='Book shelf', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Book')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
