# Generated by Django 2.1.3 on 2019-02-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190226_0424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBooks',
            new_name='UserBook',
        ),
    ]
