# Generated by Django 2.1.3 on 2019-02-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_userbook_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('n', 'none'), ('c', 'Currently reading'), ('r', 'Read'), ('w', 'want to read')], default='n', help_text='Book shelf', max_length=1),
        ),
    ]
