# Generated by Django 2.1.3 on 2019-02-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190226_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='status',
            new_name='shelf',
        ),
    ]
