# Generated by Django 2.1.3 on 2019-02-27 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_auto_20190226_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='desciption',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('book', 'reader')},
        ),
    ]
