# Generated by Django 2.1.3 on 2019-02-27 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190227_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email_id',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(max_length=3000),
        ),
    ]
