# Generated by Django 2.1.7 on 2019-03-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190227_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to='cover_pic'),
        ),
    ]
