# Generated by Django 2.1.7 on 2019-04-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='greads/static/image/profile.png', upload_to='profile_picture'),
        ),
    ]
